CREATE TABLE BANKEMPLOYEE(
USERNAME VARCHAR2(30) PRIMARY KEY,
PASS VARCHAR2(30) NOT NULL
);

CREATE TABLE BANKADMIN(
USERNAME VARCHAR2(30) PRIMARY KEY,
PASS VARCHAR2(30) NOT NULL
);

CREATE TABLE BANKACCOUNT (
ACCID NUMBER PRIMARY KEY,
ACTIVE VARCHAR2(1) NOT NULL,
BALANCE NUMBER
);

CREATE TABLE BANKCUSTOMER (
CUSTOMERID NUMBER PRIMARY KEY,
USERNAME VARCHAR2(30) UNIQUE NOT NULL,
PASS VARCHAR2(30) NOT NULL,
NAME VARCHAR2(30) NOT NULL,
LAST VARCHAR2(30) NOT NULL
);

CREATE TABLE BANKACCHOLDERS (
CUSTOMERID NUMBER,
ACCID NUMBER
);