CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INTEGER PRIMARY KEY,
    FIRSTNAME VARCHAR2(20),
    LASTNAME VARCHAR2(30),
    SOCIAL_S INTEGER,
    USER_NAME VARCHAR2(50),
    CUSTOMER_PASSWORD VARCHAR2(30),
    EMAIL VARCHAR2(50),
    ACCOUNT_ID INTEGER);
    COMMIT;
    
CREATE TABLE ACCOUNTS(
    ACCOUNT_ID INTEGER NOT NULL,
    BALANCE INTEGER,
    CONSTRAINT PK_ACCOUNT_ID PRIMARY KEY (ACCOUNT_ID),
    ACTIVE VARCHAR2(1) NOT NULL);
    
INSERT INTO CUSTOMERS(CUSTOMER_ID) VALUES(1);

UPDATE CUSTOMERS SET FIRSTNAME = 'ALEX' WHERE CUSTOMER_ID = 1;
UPDATE CUSTOMERS SET USER_NAME = 'JOHNDOE', CUSTOMER_PASSWORD = 'JOHNDOE123' WHERE CUSTOMER_ID = 1;

DROP TABLE CUSTOMERS;
COMMIT;

ALTER TABLE ACCOUNTS ADD CONSTRAINT FK_ACCOUNT_ID
    FOREIGN KEY (ACCOUNT_ID) REFERENCES CUSTOMERS (CUSTOMER_ID);

CREATE SEQUENCE CUSTOMERSEQ;
CREATE SEQUENCE ACCOUNTSEQ;

CREATE OR REPLACE PROCEDURE INSERTCUSTOMER(FIRSTNAME IN VARCHAR2, LASTNAME IN VARCHAR2, SOCIAL_S IN NUMBER, 
USER_NAME IN VARCHAR2, CUSTOMER_PASSWORD IN VARCHAR2, EMAIL IN VARCHAR2)
AS
BEGIN
INSERT INTO CUSTOMERS VALUES(CUSTOMERSEQ.NEXTVAL, FIRSTNAME, LASTNAME, SOCIAL_S, 
USER_NAME, CUSTOMER_PASSWORD, EMAIL, ACCOUNTSEQ.NEXTVAL);
COMMIT;
END;
/

EXECUTE INSERTCUSTOMER('DUMMY', 'DUMMY', 1234567891, 'DUMMY', 'DUMMY123', 'DUMMYGMAIL');

ALTER TABLE ACCOUNTS ADD USER_NAME VARCHAR2(50);