CREATE OR REPLACE PROCEDURE INSERTADMIN(USERNAME IN VARCHAR2, PASSWORD IN VARCHAR2)
AS
BEGIN
INSERT INTO BANKADMIN VALUES(USERNAME, PASSWORD);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE CLEARADMIN
AS 
BEGIN
DELETE FROM BANKADMIN
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERTEMPLOYEE(USERNAME IN VARCHAR2, PASSWORD IN VARCHAR2)
AS
BEGIN
INSERT INTO BANKEMPLOYEE VALUES(USERNAME, PASSWORD);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE CLEAREMPLOYEE
AS 
BEGIN
DELETE FROM BANKEMPLOYEE
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERTACCOUNT(ACCID IN NUMBER, ACTIVE IN VARCHAR2, BALANCE IN NUMBER)
AS
BEGIN
INSERT INTO BANKACCOUNT VALUES(ACCID, ACTIVE, BALANCE);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE CLEARACCOUNTS
AS 
BEGIN
DELETE FROM BANKACCOUNT
COMMIT;
END;
/


CREATE OR REPLACE PROCEDURE INSERTACCHOLDER(CUSTOMERID IN NUMBER, ACCID IN VARCHAR2)
AS
BEGIN
INSERT INTO BANKACCHOLDERS VALUES(CUSTOMERID, ACCID);
COMMIT;
END;
/
EXECUTE INSERTACCHOLDER(0,0);

CREATE OR REPLACE PROCEDURE CLEARACCHOLDERS
AS 
BEGIN
DELETE FROM BANKACCHOLDERS
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE INSERTCUSTOMER(CUSTOMERID IN NUMBER,
USERNAME IN VARCHAR2, PASSWORD IN VARCHAR2,
NAME IN VARCHAR2, LAST IN VARCHAR2)
AS
BEGIN
INSERT INTO BANKCUSTOMER VALUES(CUSTOMERID, USERNAME, PASSWORD, NAME, LAST);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE CLEARCUSTOMER
AS 
BEGIN
DELETE FROM BANKCUSTOMER
COMMIT;
END;
/

