CREATE TABLE BANKCUSTOMERS (
CUSTOMERID VARCHAR2(30) PRIMARY KEY,
USERNAME VARCHAR2(30),
PASSWORD VARCHAR2(30),
NAME VARCHAR2(30),
SOCIAL VARCHAR2(30)
);
/
CREATE TABLE BANKACCOUNTS (
ACCOUNTID VARCHAR2(30) PRIMARY KEY,
BALANCE VARCHAR2(30)
);
/

ALTER TABLE BANKACCOUNTS
ADD CUSTOMERID VARCHAR2(30);



ALTER TABLE BANKACCOUNTS
ADD CONSTRAINT FK_CUSTID
FOREIGN KEY (CUSTOMERID) REFERENCES BANKCUSTOMERS(CUSTOMERID) ON DELETE CASCADE;

/
CREATE OR REPLACE PROCEDURE INSERTCUSTOMER(CU_ID IN VARCHAR2,CU_US IN VARCHAR2, CU_PS IN VARCHAR2,CU_NM IN VARCHAR2,CU_SC IN VARCHAR2)
AS
BEGIN
INSERT INTO BANKCUSTOMERS VALUES(CU_ID,CU_US,CU_PS,CU_NM,CU_SC);
COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE BANKINSERT(ACCID IN VARCHAR2, BALZ IN VARCHAR2, CUSTID IN VARCHAR2)
AS
BEGIN
INSERT INTO BANKACCOUNTS VALUES(ACCID, BALZ, CUSTID);
COMMIT;
END;
/
CREATE OR REPLACE PROCEDURE BANKUPDATE(BALZ IN VARCHAR2, CUSTID IN VARCHAR2)
AS
BEGIN
UPDATE BANKACCOUNTS
SET  BALANCE = BALZ 
WHERE CUSTOMERID = CUSTID;
COMMIT;
END;


CREATE OR REPLACE PROCEDURE USERDELETE(CUSTID IN VARCHAR2)
AS
BEGIN
DELETE FROM BANKCUSTOMERS WHERE CUSTID = CUSTID;

COMMIT;
END;