CREATE TABLE RE_EMPLOYEE(
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    FIRSTNAME VARCHAR2(30) NOT NULL,
    LASTNAME VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(50) NOT NULL,
    CUSTOMER_PASSWORD VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(50),
    LEFTOVER NUMBER NOT NULL,
    SUPERVISOR_ID INTEGER,
    CLEARANCE INTEGER NOT NULL);
    COMMIT;
    
    
CREATE TABLE REIMBURSEMENT(
    REIMBUREMENT_ID INTEGER PRIMARY KEY,
    EMPLOYEE_ID INTEGER NOT NULL,
    RE_DATE DATE NOT NULL,
    APPROVAL_STATUS INTEGER NOT NULL,
    RE_COST NUMBER NOT NULL,
    RE_LOCATION VARCHAR2 (50) NOT NULL,
    GRADING_FORMAT INTEGER NOT NULL,
    EVENT_TYPE INTEGER NOT NULL,
    JUSTIFICATION VARCHAR2 (50) NOT NULL,
    RE_UPLOAD BLOB);
    COMMIT;
    
ALTER TABLE REIMBURSEMENT ADD IN_CHARGE INTEGER NOT NULL;
ALTER TABLE REIMBURSEMENT ADD RE_REQUEST VARCHAR2 (300) NOT NULL;
ALTER TABLE REIMBURSEMENT ADD DENY_REASON VARCHAR2 (300) NOT NULL;