CREATE TABLE RE_EMPLOYEE(
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    FIRSTNAME VARCHAR2(30) NOT NULL,
    LASTNAME VARCHAR2(30) NOT NULL,
    USER_NAME VARCHAR2(50) NOT NULL,
    CUSTOMER_PASSWORD VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(50),
    LEFTOVER NUMBER NOT NULL,
    SUPERVISOR_ID INTEGER,
    CLEARANCE INTEGER NOT NULL);
    COMMIT;
    
    
CREATE TABLE REIMBURSEMENT(
    REIMBUREMENT_ID INTEGER PRIMARY KEY,
    EMPLOYEE_ID INTEGER NOT NULL,
    RE_DATE DATE NOT NULL,
    APPROVAL_STATUS INTEGER NOT NULL,
    RE_COST NUMBER NOT NULL,
    RE_LOCATION VARCHAR2 (50) NOT NULL,
    GRADING_FORMAT INTEGER NOT NULL,
    EVENT_TYPE INTEGER NOT NULL,
    JUSTIFICATION VARCHAR2 (50) NOT NULL,
    RE_UPLOAD BLOB);
    COMMIT;
    
ALTER TABLE REIMBURSEMENT ADD IN_CHARGE INTEGER NOT NULL;
ALTER TABLE REIMBURSEMENT ADD RE_REQUEST VARCHAR2 (300) NOT NULL;
ALTER TABLE REIMBURSEMENT ADD DENY_REASON VARCHAR2 (300) NOT NULL;


CREATE OR REPLACE PROCEDURE INSERTREIMBURS(EMPLOYEEID NUMBER, RE_DATE DATE, APPROVAL_STATUS NUMBER, RE_COST NUMBER,
    RE_LOCATION VARCHAR2, GRADING_FORMAT NUMBER, EVENT_TYPE NUMBER, JUSTIFICATION VARCHAR2, IN_CHARGE NUMBER, DENY_REASON VARCHAR2, RE_UPLOAD BLOB)
AS
BEGIN
INSERT INTO REIMBURSEMENT VALUES(REIMBURSESEQ.NEXTVAL, RE_DATE, APPROVAL_STATUS, RE_COST,
    RE_LOCATION, GRADING_FORMAT, EVENT_TYPE, JUSTIFICATION, IN_CHARGE, DENY_REASON, RE_UPLOAD);
COMMIT;
END;
/

CREATE SEQUENCE EMPLOYSEQ;
CREATE SEQUENCE REIMBURSESEQ;

