CREATE TABLE CUSTOMER_BANK_APP (
    CustomerID NUMBER NOT NULL,
    Username VARCHAR2(64) NOT NULL,
    Password VARCHAR2(64) NOT NULL,
    FirstName VARCHAR2(64) NOT NULL,
    LastName VARCHAR2(64) NOT NULL,
    CONSTRAINT PK_CUSTOMER_BANK_APP PRIMARY KEY (CustomerID)
);

CREATE TABLE ACCOUNT_BANK_APP (
    AccountID NUMBER NOT NULL,
    CustomerID NUMBER NOT NULL,
    Balance NUMBER(12, 2) NOT NULL,
    CONSTRAINT PK_ACCOUNT_BANK_APP PRIMARY KEY (AccountID)
);

ALTER TABLE ACCOUNT_BANK_APP
ADD CONSTRAINT FK_CustomerID
FOREIGN KEY (CustomerID)
REFERENCES CUSTOMER_BANK_APP (CustomerID);

ALTER TABLE ACCOUNT_BANK_APP
ADD CONSTRAINT BALANCE_POSITIVE
CHECK (Balance >= 0);

ALTER TABLE CUSTOMER_BANK_APP
ADD CONSTRAINT UNIQUE_USERNAME
UNIQUE (Username);

CREATE SEQUENCE CUSTOMER_ID;

CREATE SEQUENCE ACCOUNT_ID;

INSERT INTO CUSTOMER_BANK_APP
VALUES (CUSTOMER_ID.NEXTVAL, 'a', 'a', 'a', 'a');
INSERT INTO CUSTOMER_BANK_APP
VALUES (CUSTOMER_ID.NEXTVAL, 'b', 'a', 'a', 'a');

INSERT INTO ACCOUNT_BANK_APP
VALUES (ACCOUNT_ID.NEXTVAL, 1, 0);