-- James Donlevy
-- Chinook Lab


--2.1 SELECT

SELECT * FROM EMPLOYEE;

SELECT * FROM EMPLOYEE
WHERE LASTNAME = 'King';

SELECT * FROM EMPLOYEE
WHERE FIRSTNAME='Andrew' 
AND REPORTSTO IS NULL;

--2.2 ORDER BY

SELECT * FROM ALBUM
ORDER BY TITLE DESC;

SELECT FIRSTNAME FROM CUSTOMER
ORDER BY CITY;

--2.3 INSERT INTO

INSERT INTO GENRE VALUES(26,'Indie Rock');
INSERT INTO GENRE VALUES(27,'Electric House');

INSERT INTO EMPLOYEE VALUES(9,'Donlevy','James','Associate Engineer',6,'05-JUL-95','11-FEB-19','20 Woodstock pl','Lake Grove','NY','Merica','11755','1234567890','who still uses fax?','username@aim.com');
INSERT INTO EMPLOYEE VALUES(10,'Morty','Smith','President',1,'05-JUL-95','01-AUG-45','1 Alamo dr','El Paso','Texas','Merica','22369','0987654321','whats a fax?','shaunPenn@myspace.com');

INSERT INTO CUSTOMER VALUES(60,'Joe','Shmo','Nike','123 Shoe walk','Beaverton','Oregon','USA','96321','1235468888','fax shouldnt exist','joe.shmo@nike.shoe',7);
INSERT INTO CUSTOMER VALUES(61,'Albert','Rho','Nvidia','555 Wafer way','Silicon Valley','California','MERICA','21216','1111111111','just no','gtx@1080.ti',4);

--2.4 UPDATE

UPDATE CUSTOMER
SET FIRSTNAME='Robert',LASTNAME='Walter'
WHERE FIRSTNAME='Aaron' AND LASTNAME='Mitchell';

UPDATE ARTIST
SET NAME='CCR'
WHERE NAME='Creedence Clearwater Revival';

--2.5 like

SELECT * FROM INVOICE
WHERE BILLINGADDRESS LIKE 'T%';

--2.6 BETWEEN

SELECT * FROM INVOICE
WHERE TOTAL BETWEEN 15 AND 50;

SELECT * FROM EMPLOYEE
WHERE HIREDATE BETWEEN '01-JUN-03' AND '01-MAR-04';

-- 2.7 DELETE

COMMIT;

DELETE FROM INVOICELINE
WHERE INVOICEID IN 
   (SELECT INVOICEID FROM INVOICE
    WHERE CUSTOMERID IN
        (SELECT CUSTOMERID FROM CUSTOMER
         WHERE FIRSTNAME='Robert' AND LASTNAME='Walter')
    );

DELETE FROM INVOICE
WHERE CUSTOMERID IN 
    (SELECT CUSTOMERID FROM CUSTOMER
    WHERE FIRSTNAME='Robert' AND LASTNAME ='Walter');

DELETE FROM CUSTOMER 
WHERE FIRSTNAME='Robert' AND LASTNAME='Walter';

COMMIT;

--3.1 SYSTEM DEFINED FUNCTIONS

CREATE OR REPLACE FUNCTION CUR_TIME
RETURN VARCHAR2
IS TIME_NOW VARCHAR2(9);
BEGIN
SELECT CURRENT_TIMESTAMP() INTO TIME_NOW
FROM DUAL;
RETURN(TIME_NOW);
END;
/

SELECT CUR_TIME() FROM DUAL;


--3.2 SYSTEM DEFINED AGGREGATE FUNCTIONS

CREATE OR REPLACE FUNCTION AVG_INVOICE
RETURN NUMBER AS AVG_IN NUMBER(10,2);
BEGIN
SELECT AVG(TOTAL) INTO AVG_IN
FROM INVOICE;
RETURN AVG_IN;
END;
/
SELECT AVG_INVOICE FROM DUAL;

CREATE OR REPLACE FUNCTION MOST_EXPENSIVE_TRACK
RETURN NUMBER AS TRACK_NAME NUMBER(10,2);
BEGIN
    SELECT MAX(UNITPRICE) INTO TRACK_NAME
    FROM TRACK;
RETURN TRACK_NAME;
END;
/
SELECT MOST_EXPENSIVE_TRACK FROM DUAL;

--3.3 USER DEFINED SCALAR FUNCTIONS
CREATE OR REPLACE FUNCTION AVG_INVOICELINE_ITEMS
RETURN NUMBER AS AVG_ITEM NUMBER(10,2);
BEGIN
    SELECT AVG(UNITPRICE) INTO AVG_ITEM
    FROM INVOICELINE;
RETURN AVG_ITEM;
END;
/
SELECT AVG_INVOICELINE_ITEMS FROM DUAL;

--4.1 BASIC STORED PROCECURE

CREATE OR REPLACE PROCEDURE FIRST_LAST(
O_FIRSTNAME OUT EMPLOYEE.FIRSTNAME%TYPE,
O_LASTNAME OUT EMPLOYEE.LASTNAME%TYPE)
IS BEGIN
SELECT FIRSTNAME, LASTNAME
INTO O_FIRSTNAME, O_LASTNAME
FROM EMPLOYEE;
END;
/
EXECUTE FIRST_LAST();

--TRANS
COMMIT;
CREATE OR REPLACE PROCEDURE DELETE_INVOICE(
    I_INVOICEID IN INVOICE.INVOICEID%TYPE)
IS BEGIN
    DELETE FROM INVOICELINE
    WHERE I_INVOICEID IN INVOICEID;
    DELETE FROM INVOICE
    WHERE INVOICEID=I_INVOICEID;
END;
/
EXECUTE DELETE_INVOICE(1);
ROLLBACK;

CREATE SEQUENCE CUSTOMERID_SEQ
MINVALUE 1
MAXVALUE 10000
START WITH 61
INCREMENT BY 1
CACHE 20;

CREATE OR REPLACE PROCEDURE ADD_NEW_CUSTOMER(
    I_FIRSTNAME IN CUSTOMER.FIRSTNAME%TYPE,
    I_LASTNAME IN CUSTOMER.LASTNAME%TYPE,
    I_COMPANY IN CUSTOMER.COMPANY%TYPE,
    I_ADDRESS IN CUSTOMER.ADDRESS%TYPE,
    I_CITY IN CUSTOMER.CITY%TYPE,
    I_STATE IN VARCHAR2,
    I_COUNTRY IN CUSTOMER.COUNTRY%TYPE,
    I_POSTALCODE IN CUSTOMER.POSTALCODE%TYPE,
    I_PHONE IN CUSTOMER.PHONE%TYPE,
    I_FAX IN CUSTOMER.FAX%TYPE,
    I_EMAIL IN CUSTOMER.EMAIL%TYPE,
    I_SUPPORTREPID IN CUSTOMER.SUPPORTREPID%TYPE)
IS BEGIN
    INSERT INTO CUSTOMER VALUES(CUSTOMERID_SEQ.NEXTVAL,
                                I_FIRSTNAME,
                                I_LASTNAME,
                                I_COMPANY,
                                I_ADDRESS,
                                I_CITY,
                                I_STATE,
                                I_COUNTRY,
                                I_POSTALCODE,
                                I_PHONE,
                                I_FAX,
                                I_EMAIL,
                                I_SUPPORTREPID);
    COMMIT;
END;
/

INSERT INTO CUSTOMER VALUES(65,
                                'WEFWEF',
                               'WEFWEF',
                                'WEFWEF',
                                'WEFWEF',
                                'WEFWE',
                                'WEFWE',
                                'WEFW',
                                'EWFEW',
                                'SDFEW',
                                'SDF',
                                'SDF',
                                4);


--7.1 INNER
SELECT C.FIRSTNAME, C.LASTNAME, I.INVOICEID
FROM CUSTOMER C
INNER JOIN INVOICE I 
ON C.CUSTOMERID=I.CUSTOMERID;

--7.2 OUTER
SELECT C.CUSTOMERID, C.FIRSTNAME, C.LASTNAME, I.INVOICEID, I.TOTAL
FROM CUSTOMER C
FULL OUTER JOIN INVOICE I
ON C.CUSTOMERID=I.CUSTOMERID;

--7.3 RIGHT
SELECT R.NAME, L.TITLE
FROM ALBUM L
RIGHT JOIN ARTIST R
ON L.ARTISTID=R.ARTISTID;

--7.4 CROSS
SELECT *
FROM ARTIST
CROSS JOIN ALBUM
ORDER BY ARTIST.NAME;

--7.5 SELF
SELECT *
FROM EMPLOYEE A, EMPLOYEE B;
