create TABLE STUDENT (
S_ID NUMBER,
S_NAME VARCHAR2(20),
SCH_ID NUMBER);

CREATE TABLE SCHOOL (
SCH_ID NUMBER,
SCH_NAME VARCHAR2(20));
COMMIT;

INSERT INTO SCHOOL VALUES (1,'USF');
INSERT INTO SCHOOL VALUES (2,'AL');
INSERT INTO SCHOOL VALUES (3,'TX');


INSERT INTO STUDENT VALUES (1,'STEVE',1);
INSERT INTO STUDENT VALUES (2,'ROBERT PAULSON',1);
INSERT INTO STUDENT VALUES (3,'EVE',1);
INSERT INTO STUDENT VALUES (4,'TIM',1);

SELECT * FROM SCHOOL
LEFT JOIN STUDENT
ON SCHOOL.SCH_ID = STUDENT.SCH_ID;

CREATE TABLE STUDENT2 (
ID NUMBER,
NAME VARCHAR2(20),
LAB_PARTNER NUMBER);

INSERT INTO STUDENT2 VALUES (1,'MATT',6);
INSERT INTO STUDENT2 VALUES (2,'DAVID',5);
INSERT INTO STUDENT2 VALUES (3,'DUSTIN',4);
INSERT INTO STUDENT2 VALUES (4,'AUSTIN',3);
INSERT INTO STUDENT2 VALUES (5,'FRANK',2);
INSERT INTO STUDENT2 VALUES (6,'GARRET',1);

SELECT A.NAME AS STUDENT, B.NAME AS LAB_PARTNER
FROM STUDENT2 A JOIN STUDENT2 B
ON A.LAB_PARTNER = B.ID;


SELECT CITY FROM CUSTOMER
UNION
SELECT CITY FROM EMPLOYEE;


